### ISSUE TITLE
Enable compression

### ISSUE THREAD

**Issue by radekmie** [potmdehex/homm3tools#31]
Today I've tried using `h3m_compress` function and found out, that the compression currently disabled completely with flag `-DNO_ZLIB` in [here](https://github.com/potmdehex/homm3tools/blob/master/h3m/h3mlib/BUILD/gcc/makefile#L14). Then I've spend some time and it seems to be working _(after you build `gzip_utils` and link it correctly, also `-lz` was needed)_. Why it's disabled then? Is it somehow connected with Windows _(I was testing it on Linux)_.

**Comment by potmdehex** [comment]
zlib is disabled because despite the fact that I have a working implementation using it, zlib can in general be a pain to get working. Especially on Windows (for both MSVC & mingw). I simply did not want to have a required dependency on it (or any other 3rd party dependencies) for h3mlib. It might be possible to come up with a better way to have zlib as an optional dependency, but making it required is something I don't want to do.

Slightly offtopic but for the record the game and map editor both support opening both compressed and uncompressed maps. The main need to involve zlib with h3mlib at all and the reason I did so is not primarily to be able to use h3m_compress, but rather h3m_decompress as the map editor compresses maps when saving by default meaning all maps that come with the game as well as all maps available online are compressed. For this reason I cannot either simply remove zlib from the equation.

**Comment by radekmie** [comment]
How about linking it only on Linux then? Somehow I'm really interested in it because it's very useful in debugging - my maps are causing game crash _(and an in game warning about broken file)_ but are completely fine in editor. I've discovered, that when I open it in the editor and save then it's working so I'm diffing their hexes.

**Comment by potmdehex** [comment]
For starters you can of course remove -DNO_ZLIB in your own makefile for your own purposes. Another tip I have for debugging is that you can also easily decompress maps saved by editor independently of h3mlib using tools like 7-zip, 7z or gunzip. Another thing is that sometimes maps crash because of object placement (i.e two objects that should not be possible to have on top of each other are, which can happen for a few objects like towns).

I'm still a bit reluctant to link zlib by default even on Linux, and don't simply want to remove -DNO_ZLIB from those CFLAGS even if just for Linux. A more sophisticated makefile making it easy to build both with and without zlib as well as an update of README.md (since now the only instruction is "make") and possibly the source code referencing NO_ZLIB might be an option though.

**Comment by radekmie** [comment]
That's exactly what I did. OK then, I fully understand your decision.

About that bug: it must be something with the player settings - my map have (in the game) selected Castle mixed with random (random can be changed to Conflux only) and after saving it from the editor it has correct castles (these are taken from map somehow). I'm building a RoE map and currently `h3m_player_enable` is the only player-related code I'm using. Would you like me to file another issue?

**Comment by potmdehex** [comment]
Yes, sounds like a good idea to file an issue for that.
